---
spring:
    datasource:
        main:
            url: jdbc:oracle:thin:@//localhost:${DATABASE_PORT:1521}/bdd_workshop1
            username: ${DATABASE_USER:oracle}
            password: ${DATABASE_PASSWORD:oracle}

    flyway:
        main:
            url: ${spring.datasource.main.url}
            user: ${spring.datasource.main.username}
            password: ${spring.datasource.main.password}

security:
    enabled: false
