---
spring:
    datasource:
        main:
            driver-class-name: org.h2.Driver
            embedded: true
        login:
            driver-class-name: org.h2.Driver
            embedded: true
    flyway:
        baseline-on-migrate: true

security:
    authorization:
        enabled: false
